stages:
  - test
  - deploy

lint:
  image: library/node:latest
  stage: test
  script:
    - npm install
    - npm run lint

test:
  image: library/node:latest
  stage: test
  script:
    - npm install
    - npm run test

pages:
  stage: deploy
  image: library/ruby:latest
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - gem install bundler jekyll
    - bundle update rb-inotify
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm publish --verbose --access public
  rules:
    - if: $CI_COMMIT_TAG
