pages:
  stage: deploy
  image: ruby:latest
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - gem install bundler jekyll
    - bundle update rb-inotify
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG

publish:
  image: quay.imanuel.dev/dockerhub/library---node:latest
  stage: deploy
  script:
    - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
    - npm publish --verbose
  rules:
    - if: $CI_COMMIT_TAG
